spring.application.name=matkinh_db

# DATABASE CONFIGURATION (Aiven)
spring.datasource.url=jdbc:mysql://mysql-matkinh-hoangmanhhung05052005-cfd3.b.aivencloud.com:19600/defaultdb?ssl-mode=REQUIRED&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_vxzqC6pMLaDk7lb3Cuo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# UPLOAD CONFIGURATION
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Path upload (Relative path for Render)
upload.path=uploads/

# STATIC MAPPING
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# AVIF SUPPORT
spring.mvc.contentnegotiation.media-types.avif=image/avif

# THYMELEAF CONFIG
spring.thymeleaf.cache=false