spring.application.name=matkinh_db

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/matkinh_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# dùng ???ng d?n tuy?t ??i
upload.path=uploads/

# Static mapping
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# AVIF support
spring.mvc.contentnegotiation.media-types.avif=image/avif

# Disable cache
spring.thymeleaf.cache=false